#!/bin/bash
set -e
echo "update-barcodescanner"
pushd .
cd /home/pi/barcodescanner-js
git pull -r
npm install
/usr/lib/node-v6.11.0-linux-armv6l/lib/node_modules/pm2/bin/pm2 start /home/pi/barcodescanner-js/bin/www
popd